language: "perl"
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
  - "5.6"

before_install:
    - cpanm Test::Pod # optional dependency
    - cpanm Module::CPANTS::Analyse
    - cpanm Test::Kwalitee # optional dependency
